branches:
  only:
  - master
  - chore/npm
sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
install:
  - npm install
  - npm run bootstrap
script:
  - npm test -- --coverage
  - npm run lint
deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm run publish prerelease --yes -m \"chore(release): publish %s ***NO_CI***\""
  skip_cleanup: true
