sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
install:
  - npm install
  - npm run bootstrap
script:
  - npm test -- --coverage
  - npm run lint
deploy:
  on:
    all_branches: true
  provider: script
  script: "git reset --hard && git checkout ${TRAVIS_BRANCH} -f && npm run setnpmtoken && git status && npm run publish -- prerelease --yes --concurrency 1 --registry https://registry.npmjs.org --force-publish --no-verify-access --no-verify-registry -m \"chore(release): publish %s ***NO_CI***\""
  skip_cleanup: true
