sudo: required
dist: trusty
language: node_js
before_script:
  - git config --global user.email "build-ci@axa.fr"
  - git config --global user.name "Build-CI"
node_js:
  - '8'
install:
  - npm install
  - npm run bootstrap
script:
  - npm test -- --coverage
  - npm run lint
deploy:
  on:
    all_branches: true
  provider: script
  script: "git reset --hard && git remote set-url origin https://${GH_TOKEN}@github.com/AxaGuilDEv/react-oidc.git && git checkout ${TRAVIS_BRANCH} && npm run publish -- prerelease --yes --concurrency 1 --loglevel=silly --force-publish"
  skip_cleanup: true
