sudo: required
dist: trusty
language: node_js
env:
  - NPM_USER=AXA
  - NPM_PASS=${NPM_AUTH_TOKEN}
  - NPM_EMAIL=john@example.com
node_js:
  - '8'
before_install:
 - printf "registry=https://registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc
install:
  - npm install
  - npm run bootstrap
script:
  - npm test -- --coverage
  - npm run lint
deploy:
  on:
    all_branches: true
  provider: script
  script: "git reset --hard && npx npm-login-cmd  && npm run publish -- prerelease --yes --concurrency 1 --force-publish --no-verify-access --no-verify-registry -m \"chore(release): publish %s ***NO_CI***\""
  skip_cleanup: true
